### ISSUE TITLE
Missing serenity-js devDependency 

### ISSUE THREAD

**Issue by jamiejones85** [serenity-js/tutorial-from-scripts-to-serenity#5]
package.json is missing the serenity-js dependency and so the screenplay.js module cannot be imported.

**Comment by jan-molak** [comment]
Hey @jamiejones85! `serenity-js` is installed as part of [the tutorial](http://serenity-js.org/from-scripts-to-serenity/writing-what-you-would-like-to-read.html#getting-started), which highlights all the steps necessary to use the framework.

If you'd like to start the tutorial at the stage where the module is added to `package.json`, you could switch to [`1-first-scenario-implemented` branch](https://github.com/serenity-js/tutorial-from-scripts-to-serenity/tree/1-first-scenario-implemented) instead of `master`.

Hope this helps!
Jan
